const state={catalog:[],profiles:new Map(),selectedFolder:null,lastListHash:"search",accessToken:"",tokenExpiresAt:0,monitorTimer:null,lastActivityKey:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],config=window.BOOK_APP_CONFIG||{};

async function load(){const [catalog,profiles]=await Promise.all([fetchJSON("data/catalog.json"),fetchJSON("config/analysis-profiles.json")]);state.catalog=catalog.books||[];Object.entries(profiles.profiles||{}).forEach(([k,v])=>state.profiles.set(k,v));bind();route();renderSearch();renderFilters();renderBrowse();showConfigurationState();await loadJobStatus()}
async function fetchJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
function bind(){window.addEventListener("hashchange",route);$("#search-input").addEventListener("input",renderSearch);document.addEventListener("keydown",e=>{if(e.key==="/"&&!/input|textarea/i.test(document.activeElement.tagName)){e.preventDefault();location.hash="search";$("#search-input").focus()}});$("#detail-back").onclick=()=>{location.hash=state.lastListHash};$("#pick-folder").onclick=openPicker;$("#preview-index").onclick=()=>relay("preview");$("#start-index").onclick=()=>relay("dispatch");$("#connect-monitor").onclick=connectMonitor;$("#save-api-key").onclick=saveApiKey;$("#toggle-key").onclick=()=>{const input=$("#gemini-key");input.type=input.type==="password"?"text":"password";$("#toggle-key").textContent=input.type==="password"?"보기":"숨기기"}}
function route(){const [page,id]=location.hash.slice(1).split("/"),key=page||"search";$$('.view').forEach(v=>v.hidden=true);$$('[data-nav]').forEach(a=>a.classList.toggle("active",a.dataset.nav===key));if(key==="book"&&id){$("#detail-view").hidden=false;showBook(id);return}$("#"+(key==="browse"?"browse":key==="indexing"?"indexing":"search")+"-view").hidden=false;state.lastListHash=key;if(key==="indexing"&&state.accessToken)startMonitoring()}
function matches(book,q){if(!q)return true;const hay=[book.title,book.author,book.genre,book.documentType,...(book.tags||[])].join(" ").toLocaleLowerCase("ko"),needle=q.toLocaleLowerCase("ko").replace(/\s+/g,"");return hay.includes(q.toLocaleLowerCase("ko"))||hay.replace(/\s+/g,"").includes(needle)||subsequence(needle,hay.replace(/\s+/g,""))}
function subsequence(a,b){if(a.length<2)return false;let i=0;for(const c of b)if(c===a[i])i++;return i===a.length}
function renderSearch(){const q=$("#search-input").value.trim(),books=state.catalog.filter(b=>matches(b,q));$("#search-meta").textContent=q?`${books.length}권의 연결된 기록`:`현재 ${books.length}권이 색인되어 있습니다`;renderCards($("#results"),books)}
function renderCards(root,books){root.replaceChildren();if(!books.length){appendText(root,"p","조건에 맞는 책이 없습니다.","empty");return}books.forEach(book=>{const card=$("#book-card-template").content.firstElementChild.cloneNode(true);card.querySelector(".format").textContent=book.format||"book";card.querySelector(".book-type").textContent=profileLabel(book.documentType);card.querySelector("strong").textContent=book.title||"제목 미상";card.querySelector(".author").textContent=book.author||"저자 미상";card.querySelector(".tags").textContent=(book.tags||[]).slice(0,3).map(x=>`#${x}`).join(" ");card.querySelector(".status").textContent=book.metadataStatus==="NEEDS_METADATA_REVIEW"?"메타데이터 확인 필요":"분석 완료";card.onclick=()=>location.hash=`book/${encodeURIComponent(book.bookId)}`;root.append(card)})}
function profileLabel(k){return state.profiles.get(k)?.label||k||"일반 문서"}
function renderFilters(){const root=$("#profile-filters"),values=["all",...new Set(state.catalog.map(b=>b.documentType))];values.forEach((value,i)=>{const b=document.createElement("button");b.textContent=value==="all"?"전체":profileLabel(value);b.classList.toggle("active",i===0);b.onclick=()=>{$$("#profile-filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderBrowse(value)};root.append(b)})}
function renderBrowse(type="all"){const books=type==="all"?state.catalog:state.catalog.filter(b=>b.documentType===type);$("#browse-count").textContent=`${books.length}권`;renderCards($("#browse-results"),books)}
async function showBook(id){const base=`data/books/${encodeURIComponent(id)}`;try{const [m,s,a,t,r,c]=await Promise.all(["manifest.json","summary.json","analysis.json","timeline.json","relationships.json","chunks.json"].map(x=>fetchJSON(`${base}/${x}`)));renderDetail(m,{summary:s,analysis:a,timeline:t,relationships:r,chunks:c})}catch(e){$("#detail-content").textContent=`책 정보를 읽지 못했습니다: ${e.message}`}}
function renderDetail(m,data){const h=$("#detail-header");h.replaceChildren();const left=document.createElement("div");appendText(left,"p",profileLabel(m.documentType),"eyebrow");appendText(left,"h1",m.title||"제목 미상");appendText(left,"p",`${m.author||"저자 미상"} · ${m.genre||m.documentType}`);h.append(left);if(m.source?.webViewLink){const a=document.createElement("a");a.href=m.source.webViewLink;a.target="_blank";a.rel="noopener noreferrer";a.textContent="Google Drive에서 원본 열기 ↗";h.append(a)}const tabs=$("#detail-tabs");tabs.replaceChildren();const defs=m.tabs||[{key:"summary",label:"전체 요약"}];defs.forEach((tab,i)=>{const b=document.createElement("button");b.role="tab";b.textContent=tab.label;b.classList.toggle("active",i===0);b.onclick=()=>{$$("#detail-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");showTab(tab.key,data)};tabs.append(b)});showTab(defs[0].key,data)}
function showTab(key,data){const root=$("#detail-content");root.replaceChildren();let value;if(key==="summary")value=data.summary;else if(key==="sections")value=data.analysis.sections||data.chunks.chunks;else if(key==="timeline")value=data.timeline.timeline;else if(key==="relationships")value=data.relationships.relationships;else value=data.analysis.analysis?.[key]||[];appendValue(root,value,key)}
function appendValue(root,value,label){if(value==null||value===""){appendText(root,"p","이 항목에는 확인된 분석이 없습니다.","empty");return}if(typeof value==="string"){appendText(root,"p",value);return}if(Array.isArray(value)){const list=document.createElement("div");list.className="data-list";value.forEach(v=>{const item=document.createElement("div");item.className="data-item";appendValue(item,v,label);list.append(item)});root.append(list);return}if(typeof value==="object"){Object.entries(value).forEach(([k,v])=>{if(k==="sourceChunkIds"){appendText(root,"small",`근거 구간: ${[].concat(v).join(", ")}`);return}appendText(root,"h3",humanize(k));appendValue(root,v,k)});return}appendText(root,"span",String(value))}
function humanize(k){return({summaryShort:"짧은 요약",summaryLong:"상세 요약",summary:"요약",description:"설명",uncertainties:"불확실성"}[k]||k.replace(/([A-Z])/g," $1"))}
function appendText(root,tag,text,className){const el=document.createElement(tag);if(className)el.className=className;el.textContent=text;root.append(el);return el}

function missingSettings(items){return items.filter(([,v])=>!v||String(v).startsWith("REPLACE_")).map(([name])=>name)}
function oauthConfigurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId]])}
function pickerConfigurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId],["Google Picker API Key",config.googlePickerApiKey]])}
function configurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId],["Google Picker API Key",config.googlePickerApiKey],["Apps Script Web App URL",config.appsScriptWebAppUrl]])}
function showConfigurationState(){const issues=configurationIssues(),alert=$("#setup-alert");if(!issues.length){alert.hidden=true;return}alert.hidden=false;alert.textContent=`관리 기능 설정이 아직 끝나지 않았습니다: ${issues.join(", ")}. README의 ‘Picker와 Apps Script 연결’ 단계를 완료해야 폴더 선택·API 키 저장·실시간 모니터가 작동합니다.`}
async function waitForGoogleScripts(){const limit=Date.now()+12000;while(Date.now()<limit){if(window.google?.accounts?.oauth2&&window.gapi)return;await new Promise(r=>setTimeout(r,250))}throw new Error("Google 로그인 스크립트를 불러오지 못했습니다. 광고 차단을 끄고 새로고침하세요.")}
async function getAccessToken(forceConsent=false){const issues=oauthConfigurationIssues();if(issues.length)throw new Error(`설정 필요: ${issues.join(", ")}`);if(state.accessToken&&Date.now()<state.tokenExpiresAt-60000)return state.accessToken;await waitForGoogleScripts();return new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:config.googleClientId,scope:"openid email https://www.googleapis.com/auth/drive.readonly",callback:r=>{if(r.error||!r.access_token){reject(new Error(r.error_description||r.error||"Google 인증 실패"));return}state.accessToken=r.access_token;state.tokenExpiresAt=Date.now()+Number(r.expires_in||3600)*1000;$("#monitor-connection").textContent="Google 계정 연결됨 · 5초마다 자동 갱신";startMonitoring();resolve(state.accessToken)},error_callback:e=>reject(new Error(e.message||e.type||"Google 로그인 창을 열지 못했습니다."))});client.requestAccessToken({prompt:forceConsent?"consent":""})})}
function loadPickerApi(){return new Promise((resolve,reject)=>{let settled=false;const finish=fn=>value=>{if(!settled){settled=true;fn(value)}};gapi.load("picker",{callback:finish(resolve),onerror:finish(()=>reject(new Error("Google Picker를 불러오지 못했습니다."))),timeout:12000,ontimeout:finish(()=>reject(new Error("Google Picker 응답 시간이 초과되었습니다.")))})})}
async function openPicker(){const button=$("#pick-folder");button.disabled=true;message("Google 로그인과 폴더 선택기를 준비하고 있습니다…");try{const issues=pickerConfigurationIssues();if(issues.length)throw new Error(`설정 필요: ${issues.join(", ")}`);const token=await getAccessToken();await loadPickerApi();buildPicker(token)}catch(e){message(`폴더 선택 실패: ${e.message}`);$("#setup-alert").hidden=false;$("#setup-alert").textContent=`Google Drive 폴더 선택을 시작하지 못했습니다. ${e.message}`}finally{button.disabled=false}}
function buildPicker(token){const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);if(config.driveRootFolderId&&!config.driveRootFolderId.startsWith("REPLACE_"))view.setParent(config.driveRootFolderId);new google.picker.PickerBuilder().setOAuthToken(token).setDeveloperKey(config.googlePickerApiKey).setOrigin(location.origin).addView(view).setCallback(data=>{if(data.action===google.picker.Action.PICKED){const d=data.docs[0];state.selectedFolder={id:d.id,name:d.name};$("#folder-info dd").textContent=`${d.name} (${d.id})`;$("#preview-index").disabled=false;$("#start-index").disabled=false;message("폴더가 선택되었습니다. 먼저 대상 미리 보기를 권장합니다.")}else if(data.action===google.picker.Action.CANCEL)message("폴더 선택을 취소했습니다.")}).build().setVisible(true)}
async function relayRequest(payload,requireToken=true){if(!config.appsScriptWebAppUrl||config.appsScriptWebAppUrl.startsWith("REPLACE_"))throw new Error("Apps Script Web App URL이 설정되지 않았습니다.");const accessToken=requireToken?await getAccessToken():"";const response=await fetch(config.appsScriptWebAppUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...payload,...(accessToken?{accessToken}:{})})});if(!response.ok)throw new Error(`Apps Script HTTP ${response.status}`);const data=await response.json();if(!data.ok)throw new Error(data.error||"요청 실패");return data}
async function relay(route){if(!state.selectedFolder){message("먼저 Google Drive 폴더를 선택하세요.");return}message(route==="preview"?"대상을 확인하는 중…":"GitHub Actions를 요청하는 중…");try{const data=await relayRequest({route,folderId:state.selectedFolder.id,recursive:$("#recursive").checked,force:$("#force-reindex").checked});message(route==="preview"?`대상 TXT/EPUB ${data.targetFiles}개 · 하위 폴더 ${data.folders}개`:`작업 요청 완료 · GitHub 실행 ID ${data.runId||"확인 중"}`);if(route==="dispatch")startMonitoring()}catch(e){message(`요청 실패: ${e.message}`)}}
async function saveApiKey(){const input=$("#gemini-key"),key=input.value.trim(),output=$("#api-key-message");if(!/^[A-Za-z0-9_-]{20,200}$/.test(key)){output.textContent="올바른 Gemini API Key를 입력하세요.";return}$("#save-api-key").disabled=true;output.textContent="Google 계정을 확인하고 안전하게 저장하는 중…";try{const data=await relayRequest({route:"update-api-key",geminiApiKey:key});input.value="";input.type="password";$("#toggle-key").textContent="보기";output.textContent=`저장 완료 · ${data.geminiKey.masked} · 다음 실행부터 사용`}catch(e){output.textContent=`저장 실패: ${e.message}`}finally{$("#save-api-key").disabled=false}}
async function connectMonitor(){const output=$("#monitor-connection");output.textContent="Google 계정 확인 중…";try{await getAccessToken();await pollLiveStatus()}catch(e){output.textContent=`연결 실패: ${e.message}`}}
async function loadJobStatus(){try{renderJobStatus(await fetchJSON("data/job-status.json"),false)}catch(e){$("#job-status").textContent="저장된 작업 상태를 불러오지 못했습니다."}}
function startMonitoring(){if(state.monitorTimer)clearInterval(state.monitorTimer);pollLiveStatus();state.monitorTimer=setInterval(pollLiveStatus,5000)}
async function pollLiveStatus(){if(!state.accessToken||location.hash.slice(1).split("/")[0]!=="indexing")return;try{const data=await relayRequest({route:"status"});renderJobStatus(data.progress||{},true);const key=data.geminiKey||{};$("#api-key-message").textContent=key.configured?`저장된 키: ${key.masked}`:"Apps Script에 별도로 저장된 키가 없습니다. 현재 GitHub Secret을 사용합니다."}catch(e){$("#monitor-connection").textContent=`실시간 갱신 실패: ${e.message}`}}
const phaseLabels={WAITING:"대기",QUEUED:"실행 대기",DISCOVERY_COMPLETE:"파일 목록 확인",STARTING_BOOK:"책 처리 시작",UNCHANGED:"변경 없음",DOWNLOADING:"Drive 다운로드",METADATA:"제목·저자 판별",CLASSIFYING:"문서 유형 분류",ANALYZING_CHUNK:"원문 구간 분석",SYNTHESIZING:"전체 분석 통합",SAVING:"결과 저장",BOOK_FINISHED:"책 처리 완료",BOOK_ERROR:"책 처리 오류",COMPLETE:"전체 완료",PAUSED_RATE_LIMIT:"무료 한도 일시정지",NO_SUPPORTED_MODEL:"지원 모델 없음"};
function renderJobStatus(s,live){const root=$("#job-status");root.replaceChildren();const total=Number(s.totalFiles||0),index=Number(s.currentFileIndex||0),percent=total?Math.min(100,index/total*100):0;$("#overall-progress").style.width=`${percent}%`;$("#progress-caption").textContent=total?`전체 ${total.toLocaleString()}개 중 ${index.toLocaleString()}번째 · ${percent.toFixed(2)}%`:"대상 파일 수를 확인하는 중입니다.";const indicator=$("#live-indicator");indicator.textContent=live?"실시간 · 5초 갱신":"저장된 상태";indicator.classList.toggle("live",live);const rows=[["상태",s.status||"-"],["현재 단계",phaseLabels[s.phase]||s.phase||"-"],["선택 모델",s.model||"아직 선택 전"],["현재 파일",s.currentFileName||"-"],["파일 순서",total?`${index} / ${total}`:"-"],["현재 청크",s.totalChunks?`${s.currentChunk||0} / ${s.totalChunks}`:"-"],["완료",s.complete??0],["건너뜀",s.skipped??0],["실패",s.failed??0],["메타 확인 필요",s.metadataReview??0],["Gemini 요청",s.apiRequests??0],["입력 토큰",Number(s.inputTokens||0).toLocaleString()],["출력 토큰",Number(s.outputTokens||0).toLocaleString()],["Drive quota units",s.driveQuotaUnits??0],["Drive 다운로드",formatBytes(s.driveDownloadedBytes)],["마지막 갱신",formatTime(s.updatedAt||s.finishedAt)]];const grid=document.createElement("div");grid.className="status-table";rows.forEach(([k,v])=>{const d=document.createElement("div");appendText(d,"small",String(k));appendText(d,"strong",String(v));grid.append(d)});root.append(grid);if(s.message)appendText(root,"p",s.message);recordActivity(s)}
function recordActivity(s){const key=[s.updatedAt,s.phase,s.currentFileName,s.currentChunk].join("|");if(!key||key===state.lastActivityKey)return;state.lastActivityKey=key;const log=$("#activity-log");if(log.children.length===1&&log.firstElementChild.textContent==="모니터 연결 대기 중")log.replaceChildren();const item=document.createElement("li");item.textContent=`${formatTime(s.updatedAt)} · ${phaseLabels[s.phase]||s.phase||s.status||"상태 변경"}${s.currentFileName?` · ${s.currentFileName}`:""}`;log.prepend(item);while(log.children.length>12)log.lastElementChild.remove()}
function formatBytes(value){const bytes=Number(value||0);if(!bytes)return"0 B";const units=["B","KB","MB","GB"],i=Math.min(units.length-1,Math.floor(Math.log(bytes)/Math.log(1024)));return`${(bytes/1024**i).toFixed(i?1:0)} ${units[i]}`}
function formatTime(value){if(!value)return"-";const date=new Date(value);return Number.isNaN(date.valueOf())?String(value):date.toLocaleString("ko-KR")}
function message(text){$("#index-message").textContent=text}
load().catch(e=>{console.error(e);$("#results").textContent=`초기 데이터를 읽지 못했습니다: ${e.message}`});
