import {loadDriveChunks} from "./source-reader.js";
import {composeCopyText,createFormatId,loadPromptFormats,savePromptFormats} from "./prompt-formats.js";

const state={catalog:[],profiles:new Map(),metadataOverrides:{},selectedFolder:null,lastListHash:"search",accessToken:"",tokenExpiresAt:0,monitorTimer:null,lastActivityKey:"",lastStatus:null,dispatching:false,queueCheckAt:0,queueResolvedStatus:null,currentBundle:null,currentTabKey:"summary",showEvidence:false,sourceChunks:new Map(),readerFontSize:17,readerLineHeight:1.8,promptFormats:[],selectedFormatId:"",editingFormatId:"",draggedFormatId:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],config=window.BOOK_APP_CONFIG||{};

async function load(){
  const [catalog,profiles,overrides,formats]=await Promise.all([fetchJSON("data/catalog.json"),fetchJSON("config/analysis-profiles.json"),fetchJSON("data/metadata-overrides.json").catch(()=>({byDriveFileId:{}})),loadPromptFormats()]);
  state.metadataOverrides=overrides.byDriveFileId||{};
  Object.entries(profiles.profiles||{}).forEach(([k,v])=>state.profiles.set(k,v));
  state.catalog=(catalog.books||[]).map(applyMetadataOverride);
  state.promptFormats=formats;state.selectedFormatId=formats[0]?.id||"";
  bind();renderFormatSelect();renderProfileOptions();route();renderSearch();renderFilters();renderBrowse();showConfigurationState();await loadJobStatus()
}
async function fetchJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
function bind(){window.addEventListener("hashchange",route);$("#search-input").addEventListener("input",renderSearch);document.addEventListener("keydown",e=>{if(e.key==="/"&&!/input|textarea|select/i.test(document.activeElement.tagName)){e.preventDefault();location.hash="search";$("#search-input").focus()}if(e.key==="Escape"){if($("#format-dialog").open)closeFormatDialog();else if($("#metadata-dialog").open)closeMetadataDialog();else if($("#chunk-dialog").open)closeChunkDialog()}});$("#detail-back").onclick=()=>{location.hash=state.lastListHash};$("#pick-folder").onclick=openPicker;$("#preview-index").onclick=()=>relay("preview");$("#start-index").onclick=()=>relay("dispatch");$("#connect-monitor").onclick=connectMonitor;$("#save-api-key").onclick=saveApiKey;$("#toggle-key").onclick=()=>{const input=$("#gemini-key");input.type=input.type==="password"?"text":"password";$("#toggle-key").textContent=input.type==="password"?"보기":"숨기기"};$("#font-smaller").onclick=()=>adjustReader("font",-1);$("#font-larger").onclick=()=>adjustReader("font",1);$("#line-tighter").onclick=()=>adjustReader("line",-.1);$("#line-looser").onclick=()=>adjustReader("line",.1);$("#toggle-evidence").onchange=e=>{state.showEvidence=e.currentTarget.checked;if(state.currentBundle)showTab(state.currentTabKey,state.currentBundle)};$("#chunk-select").onchange=()=>{if($("#chunk-select").value)openSelectedChunk()};$("#open-chunk").onclick=openSelectedChunk;$("#prompt-format-select").onchange=e=>{state.selectedFormatId=e.currentTarget.value;updateCopyTrigger()};$("#manage-formats").onclick=openFormatDialog;$("#quick-edit-format").onclick=()=>{openFormatDialog();editSelectedFormat()};$("#quick-add-format").onclick=()=>{openFormatDialog();addFormat()};$("#quick-delete-format").onclick=()=>{openFormatDialog();deleteSelectedFormat()};$("#edit-format").onclick=editSelectedFormat;$("#add-format").onclick=addFormat;$("#delete-format").onclick=deleteSelectedFormat;$("#save-format").onclick=saveFormatEditor;$("#cancel-format").onclick=closeFormatEditor;$("#close-formats").onclick=closeFormatDialog;$("#done-formats").onclick=closeFormatDialog;$("#copy-chunk").onclick=copyChunk;$("#close-chunk").onclick=closeChunkDialog;$("#close-chunk-bottom").onclick=closeChunkDialog;$("#chunk-dialog").addEventListener("click",e=>{if(e.target===$("#chunk-dialog"))closeChunkDialog()});$("#save-metadata").onclick=saveMetadata;$("#close-metadata").onclick=closeMetadataDialog;$("#cancel-metadata").onclick=closeMetadataDialog;updateReaderControls()}
function route(){const [page,id]=location.hash.slice(1).split("/"),key=page||"search";$$('.view').forEach(v=>v.hidden=true);$$('[data-nav]').forEach(a=>a.classList.toggle("active",a.dataset.nav===key));if(key==="book"&&id){$("#detail-view").hidden=false;showBook(id);return}$("#"+(key==="browse"?"browse":key==="indexing"?"indexing":"search")+"-view").hidden=false;state.lastListHash=key;if(key==="indexing"&&state.accessToken)startMonitoring()}
function matches(book,q){if(!q)return true;const hay=[book.title,book.author,book.genre,book.documentType,...(book.tags||[])].join(" ").toLocaleLowerCase("ko"),needle=q.toLocaleLowerCase("ko").replace(/\s+/g,"");return hay.includes(q.toLocaleLowerCase("ko"))||hay.replace(/\s+/g,"").includes(needle)||subsequence(needle,hay.replace(/\s+/g,""))}
function subsequence(a,b){if(a.length<2)return false;let i=0;for(const c of b)if(c===a[i])i++;return i===a.length}
function renderSearch(){const q=$("#search-input").value.trim();if(!q){$("#search-meta").textContent="검색어를 입력하면 결과가 여기에 표시됩니다.";renderBookRows($("#results"),[],"검색어를 입력하세요.");return}const books=state.catalog.filter(b=>matches(b,q));$("#search-meta").textContent=`검색 결과 ${books.length}권`;renderBookRows($("#results"),books,"조건에 맞는 책이 없습니다.")}
function renderBookRows(root,books,emptyText="등록된 책이 없습니다."){root.replaceChildren();if(!books.length){appendText(root,"p",emptyText,"empty");return}books.forEach(book=>{const row=$("#book-row-template").content.firstElementChild.cloneNode(true);row.querySelector(".format").textContent=book.format||"도서";row.querySelector(".book-type").textContent=profileLabel(book.documentType);row.querySelector("strong").textContent=book.title||"제목 미상";row.querySelector(".author").textContent=book.author||"저자 미상";row.querySelector(".tags").textContent=uniqueTags([genreLabel(book.genre),...(book.tags||[])]).slice(0,4).map(x=>`#${x}`).join(" ");row.querySelector(".status").textContent=book.metadataStatus==="NEEDS_METADATA_REVIEW"?"메타 확인 필요":"분석 완료";row.querySelector(".book-title-button").onclick=()=>location.hash=`book/${encodeURIComponent(book.bookId)}`;row.querySelector(".download-book").onclick=event=>downloadBook(book,event.currentTarget);root.append(row)})}
function uniqueTags(values){const seen=new Set();return values.map(value=>String(value||"").replace(/^#+/,"").trim()).filter(value=>{const key=value.toLocaleLowerCase("ko");if(!value||seen.has(key))return false;seen.add(key);return true})}
function profileLabel(k){return state.profiles.get(k)?.label||k||"일반 문서"}
function genreLabel(value){const key=String(value||"").trim().toLocaleLowerCase("en");return({novel:"소설",fiction:"소설",drama:"희곡",poetry:"시·시집",academic:"학술",philosophy:"철학",history:"역사",history_biography:"역사·전기",science:"과학",science_technical:"과학·기술",essay:"에세이",essay_general_nonfiction:"에세이·일반 논픽션",practical_manual:"실용",mixed_anthology:"혼합 문집",unknown:"미분류"}[key]||String(value||""))}
function renderFilters(){const root=$("#profile-filters"),values=["all",...new Set(state.catalog.map(b=>b.documentType))];values.forEach((value,i)=>{const b=document.createElement("button");b.textContent=value==="all"?"전체":profileLabel(value);b.classList.toggle("active",i===0);b.onclick=()=>{$$("#profile-filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderBrowse(value)};root.append(b)})}
function renderBrowse(type="all"){const books=type==="all"?state.catalog:state.catalog.filter(b=>b.documentType===type);$("#browse-count").textContent=`${books.length}권`;renderBookRows($("#browse-results"),books)}
function applyMetadataOverride(book){const override=state.metadataOverrides[book.driveFileId]||{};if(!Object.keys(override).length)return book;const fields=Object.fromEntries(["title","author","genre","documentType"].filter(key=>override[key]).map(key=>[key,override[key]]));if(Array.isArray(override.tags))fields.tags=override.tags;const updated={...book,...fields,metadataStatus:"confirmed"},profile=state.profiles.get(updated.documentType);if(profile){updated.analysisProfile=updated.documentType;updated.tabs=profile.tabs}return updated}
async function loadBookData(id){const base=`data/books/${encodeURIComponent(id)}`;const [manifest,summary,analysis,timeline,relationships,chunks]=await Promise.all(["manifest.json","summary.json","analysis.json","timeline.json","relationships.json","chunks.json"].map(x=>fetchJSON(`${base}/${x}`))),catalogEntry=state.catalog.find(book=>book.bookId===id),merged={...manifest,tags:Array.isArray(manifest.tags)?manifest.tags:(catalogEntry?.tags||[])};return{manifest:applyMetadataOverride(merged),summary,analysis,timeline,relationships,chunks}}
async function showBook(id){try{const bundle=await loadBookData(id);renderDetail(bundle.manifest,bundle)}catch(e){$("#detail-content").textContent=`책 정보를 읽지 못했습니다: ${e.message}`}}
function renderDetail(m,data){state.currentBundle={manifest:m,...data};state.currentTabKey="summary";const h=$("#detail-header");h.replaceChildren();const left=document.createElement("div");appendText(left,"p",profileLabel(m.documentType),"eyebrow");appendText(left,"h1",m.title||"제목 미상");appendText(left,"p",`${m.author||"저자 미상"} · ${genreLabel(m.genre)||profileLabel(m.documentType)}`);const tags=uniqueTags([genreLabel(m.genre),...(m.tags||[])]);if(tags.length)appendText(left,"p",tags.map(tag=>`#${tag}`).join(" "),"detail-tags");h.append(left);const actions=document.createElement("div");actions.className="detail-actions";const edit=document.createElement("button");edit.type="button";edit.className="edit-metadata";edit.textContent="작품 정보 편집";edit.onclick=openMetadataDialog;actions.append(edit);const download=document.createElement("button");download.type="button";download.className="download-detail";download.textContent="모든 분석 통합 TXT";download.onclick=()=>saveIntegratedText(m,data,download);actions.append(download);if(m.source?.webViewLink){const a=document.createElement("a");a.href=m.source.webViewLink;a.target="_blank";a.rel="noopener noreferrer";a.textContent="Google Drive에서 원본 열기 ↗";actions.append(a)}h.append(actions);configureChunkControl(data.chunks?.chunks||[]);updateReaderControls();const tabs=$("#detail-tabs");tabs.replaceChildren();const defs=m.tabs||[{key:"summary",label:"전체 요약"}];defs.forEach((tab,i)=>{const b=document.createElement("button");b.role="tab";b.textContent=tab.label;b.classList.toggle("active",i===0);b.onclick=()=>{$$("#detail-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");showTab(tab.key,data)};tabs.append(b)});showTab(defs[0].key,data)}

function renderProfileOptions(){const select=$("#metadata-profile");select.replaceChildren();state.profiles.forEach((profile,key)=>{const option=document.createElement("option");option.value=key;option.textContent=profile.label||key;select.append(option)})}
function openMetadataDialog(){const manifest=state.currentBundle?.manifest;if(!manifest)return;$("#metadata-title").value=manifest.title||"";$("#metadata-author").value=manifest.author||"";$("#metadata-genre").value=genreLabel(manifest.genre);$("#metadata-profile").value=manifest.documentType||"unknown";$("#metadata-tags").value=(manifest.tags||[]).join(", ");$("#metadata-message").textContent="";$("#metadata-dialog").showModal()}
function closeMetadataDialog(){const dialog=$("#metadata-dialog");if(dialog.open)dialog.close()}
async function saveMetadata(){const manifest=state.currentBundle?.manifest,button=$("#save-metadata"),output=$("#metadata-message");if(!manifest)return;const override={title:$("#metadata-title").value.trim(),author:$("#metadata-author").value.trim(),genre:$("#metadata-genre").value.trim(),documentType:$("#metadata-profile").value,tags:uniqueTags($("#metadata-tags").value.split(/[,\n]/)).slice(0,20)};if(!override.title){output.textContent="작품명을 입력하세요.";return}button.disabled=true;output.textContent="수동 수정값을 안전하게 저장하는 중…";try{const result=await relayRequest({route:"update-metadata",bookId:manifest.bookId,driveFileId:manifest.driveFileId,override});state.metadataOverrides[manifest.driveFileId]=result.override;state.catalog=state.catalog.map(book=>book.driveFileId===manifest.driveFileId?applyMetadataOverride({...book,...result.override}):book);const updatedManifest=applyMetadataOverride({...manifest,...result.override});const data={...state.currentBundle,manifest:updatedManifest};renderDetail(updatedManifest,data);renderBrowse();renderSearch();closeMetadataDialog()}catch(error){output.textContent=/Unknown route/i.test(error.message)?"Apps Script의 새 Code.gs를 배포해야 저장할 수 있습니다. README의 ‘작품 정보 편집 활성화’ 한 단계를 따라주세요.":`저장 실패: ${error.message}`}finally{button.disabled=false}}

function adjustReader(kind,delta){if(kind==="font")state.readerFontSize=Math.max(13,Math.min(28,state.readerFontSize+delta));else state.readerLineHeight=Math.max(1.3,Math.min(2.5,Number((state.readerLineHeight+delta).toFixed(1))));updateReaderControls()}
function updateReaderControls(){const content=$("#detail-content");content.style.setProperty("--reader-font-size",`${state.readerFontSize}px`);content.style.setProperty("--reader-line-height",String(state.readerLineHeight));$("#font-size-value").textContent=`${state.readerFontSize}px`;$("#line-height-value").textContent=state.readerLineHeight.toFixed(1)}
function configureChunkControl(chunks){const select=$("#chunk-select");select.replaceChildren();const empty=document.createElement("option");empty.value="";empty.textContent=chunks.length?"구간 선택":"원문 구간 없음";select.append(empty);chunks.forEach((chunk,index)=>{const option=document.createElement("option");option.value=String(chunk.chunkId||index+1);option.textContent=`${sectionLabel(chunk.chunkId||index+1)} · ${index+1} / ${chunks.length}`;select.append(option)});select.disabled=!chunks.length;$("#open-chunk").disabled=!chunks.length}
async function openSelectedChunk(){
  const bundle=state.currentBundle,select=$("#chunk-select"),chunkId=Number(select.value);
  if(!bundle||!chunkId){alert("먼저 원문 구간을 선택하세요.");return}
  const dialog=$("#chunk-dialog"),status=$("#chunk-source-status"),source=$("#chunk-source-text"),openButton=$("#open-chunk"),savedChunks=bundle.chunks?.chunks||[],total=savedChunks.length,originalButtonText=openButton.textContent;
  openButton.disabled=true;openButton.textContent="로그인 확인 중…";
  try{
    const token=await getAccessToken();
    $("#chunk-dialog-title").textContent=`${sectionLabel(chunkId)} 원문 · ${chunkId} / ${total}`;
    source.textContent="";status.textContent="Google Drive에서 원문을 안전하게 불러오는 중입니다…";
    if(!dialog.open)dialog.showModal();
    const manifest=bundle.manifest,chunking=manifest.chunking||{},cacheKey=`${manifest.driveFileId}:${manifest.source?.sha256||""}:${chunking.targetCharacters||5000}:${chunking.overlapCharacters??250}`;
    let chunks=state.sourceChunks.get(cacheKey);
    if(!chunks){chunks=await loadDriveChunks(manifest,token,Number(chunking.targetCharacters||5000),Number(chunking.overlapCharacters??250));state.sourceChunks.set(cacheKey,chunks)}
    const chunk=chunks.find(item=>Number(item.chunkId)===chunkId);
    if(!chunk)throw new Error(`원문에서 ${sectionLabel(chunkId)}을 다시 만들지 못했습니다.`);
    source.textContent=chunk.text;
    status.textContent=chunks.length===total?`${bundle.manifest.filename} · ${chunk.charCount.toLocaleString()}자 · 원문은 GitHub에 저장되지 않습니다.`:`${bundle.manifest.filename} · 현재 원문에서 ${chunks.length}개 구간을 확인했습니다. 저장된 분석 당시에는 ${total}개였습니다.`;
    source.focus()
  }catch(e){
    if(dialog.open)status.textContent=`원문을 불러오지 못했습니다: ${e.message}`;
    else alert(`Google 로그인 후 원문을 열 수 있습니다: ${e.message}`)
  }finally{openButton.disabled=false;openButton.textContent=originalButtonText}
}
async function copyChunk(){const text=$("#chunk-source-text").textContent,status=$("#chunk-source-status");if(!text){status.textContent="복사할 원문이 아직 없습니다.";return}const format=state.promptFormats.find(item=>item.id===state.selectedFormatId)||state.promptFormats[0],output=composeCopyText(format?.instruction||"",text);try{await navigator.clipboard.writeText(output);status.textContent=format?.instruction?`‘${format.name}’ 프롬프트와 원문을 함께 복사했습니다.`:"이 구간의 원문을 클립보드에 복사했습니다."}catch(e){status.textContent="브라우저가 복사를 막았습니다. 원문을 직접 선택해 복사하세요."}}
function closeChunkDialog(){const dialog=$("#chunk-dialog");if(dialog.open)dialog.close()}
function renderFormatSelect(){const select=$("#prompt-format-select");select.replaceChildren();state.promptFormats.forEach(format=>{const option=document.createElement("option");option.value=format.id;option.textContent=format.name;select.append(option)});if(!state.promptFormats.some(item=>item.id===state.selectedFormatId))state.selectedFormatId=state.promptFormats[0]?.id||"";select.value=state.selectedFormatId;updateCopyTrigger()}
function updateCopyTrigger(){const button=$("#copy-chunk"),format=state.promptFormats.find(item=>item.id===state.selectedFormatId)||state.promptFormats[0],name=format?.name||"원문만 복사";button.textContent=name;button.title=`${name} 형식으로 원문 복사`;button.setAttribute("aria-label",`${name} 형식으로 원문 복사`)}
function openFormatDialog(){closeFormatEditor();renderFormatList();$("#format-message").textContent="";$("#format-dialog").showModal()}
function closeFormatDialog(){const dialog=$("#format-dialog");if(dialog.open)dialog.close();closeFormatEditor()}
function renderFormatList(){const list=$("#format-list");list.replaceChildren();state.promptFormats.forEach(format=>{const item=document.createElement("li");item.dataset.formatId=format.id;item.classList.toggle("selected",format.id===state.selectedFormatId);const select=document.createElement("button");select.type="button";select.className="format-name-button";select.textContent=format.name;select.onclick=()=>{state.selectedFormatId=format.id;renderFormatSelect();renderFormatList()};const handle=document.createElement("span");handle.className="drag-handle";handle.textContent="≡";handle.draggable=true;handle.title="드래그해서 순서 변경";handle.setAttribute("aria-label",`${format.name} 순서 변경 손잡이`);handle.ondragstart=event=>{state.draggedFormatId=format.id;event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",format.id);item.classList.add("dragging")};handle.ondragend=()=>{state.draggedFormatId="";item.classList.remove("dragging")};item.ondragover=event=>{event.preventDefault();event.dataTransfer.dropEffect="move"};item.ondrop=event=>{event.preventDefault();reorderFormat(state.draggedFormatId||event.dataTransfer.getData("text/plain"),format.id)};item.append(select,handle);list.append(item)})}
async function reorderFormat(sourceId,targetId){if(!sourceId||sourceId===targetId)return;const from=state.promptFormats.findIndex(item=>item.id===sourceId),to=state.promptFormats.findIndex(item=>item.id===targetId);if(from<0||to<0)return;const [moved]=state.promptFormats.splice(from,1);state.promptFormats.splice(to,0,moved);await persistFormats("출력 형식 순서를 저장했습니다.")}
function addFormat(){state.editingFormatId="";$("#format-name").value="";$("#format-instruction").value="";$("#format-editor").hidden=false;$("#format-name").focus()}
function editSelectedFormat(){const format=state.promptFormats.find(item=>item.id===state.selectedFormatId);if(!format)return;state.editingFormatId=format.id;$("#format-name").value=format.name;$("#format-instruction").value=format.instruction;$("#format-editor").hidden=false;$("#format-name").focus()}
function closeFormatEditor(){$("#format-editor").hidden=true;state.editingFormatId=""}
async function saveFormatEditor(){const name=$("#format-name").value.trim(),instruction=$("#format-instruction").value.trim();if(!name){$("#format-message").textContent="출력 형식 이름을 입력하세요.";return}if(state.editingFormatId){const format=state.promptFormats.find(item=>item.id===state.editingFormatId);if(format){format.name=name;format.instruction=instruction}}else{const format={id:createFormatId(),name,instruction};state.promptFormats.push(format);state.selectedFormatId=format.id}closeFormatEditor();await persistFormats("출력 형식을 저장했습니다.")}
async function deleteSelectedFormat(){if(state.promptFormats.length<=1){$("#format-message").textContent="출력 형식은 하나 이상 남겨야 합니다.";return}const format=state.promptFormats.find(item=>item.id===state.selectedFormatId);if(!format||!confirm(`‘${format.name}’ 출력 형식을 삭제할까요?`))return;state.promptFormats=state.promptFormats.filter(item=>item.id!==format.id);state.selectedFormatId=state.promptFormats[0].id;closeFormatEditor();await persistFormats("출력 형식을 삭제했습니다.")}
async function persistFormats(messageText){try{state.promptFormats=await savePromptFormats(state.promptFormats);renderFormatSelect();renderFormatList();$("#format-message").textContent=messageText}catch(error){$("#format-message").textContent=`저장 실패: ${error.message}`}}
async function downloadBook(book,button){const original=button.textContent;button.disabled=true;button.textContent="준비 중…";try{const data=await loadBookData(book.bookId);saveIntegratedText(data.manifest,data,button)}catch(e){alert(`통합 TXT를 만들지 못했습니다: ${e.message}`)}finally{button.disabled=false;button.textContent=original}}
function saveIntegratedText(manifest,data,button){const localizedManifest={...manifest,genre:genreLabel(manifest.genre),documentType:profileLabel(manifest.documentType)};const sections=[["기본 정보 및 메타데이터",localizedManifest],["전체 요약",data.summary],["구간별 요약 및 분석",data.chunks],["장르별 종합 분석",data.analysis],["연대기·사건 흐름",data.timeline],["인물·개념 관계",data.relationships]];const header=["서재 지도 통합 분석본",`제목: ${manifest.title||"제목 미상"}`,`저자: ${manifest.author||"저자 미상"}`,`장르: ${genreLabel(manifest.genre)||"미분류"}`,`원본 파일: ${manifest.filename||"-"}`,`분석 상태: ${manifest.indexStatus||"-"}`,`분석 시각: ${manifest.indexedAt||"-"}`].join("\n");const text=header+"\n\n"+sections.map(([label,value])=>`==================== ${label} ====================\n${plainText(value)}`).join("\n\n");const blob=new Blob(["\ufeff",text],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${safeFilename(manifest.title||manifest.filename||"도서")}_통합분석.txt`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);if(button)button.textContent="다운로드 완료"}
function plainText(value,depth=0){
  const indent="  ".repeat(depth);
  if(value==null)return"-";
  if(typeof value!=="object")return displayValue(value);
  if(Array.isArray(value))return value.length?value.map(item=>`${indent}- ${typeof item==="object"?plainText(item,depth+1).trimStart():displayValue(item)}`).join("\n"):"-";
  const chunkId=Number(value.chunkId||0),lines=[];
  if(chunkId)lines.push(`${indent}${sectionLabel(chunkId)}`);
  for(const [key,item] of Object.entries(value)){
    if(["chunkId","charCount","position","uncertain"].includes(key))continue;
    if(key==="description"){lines.push(`${indent}- ${displayValue(item)}`);continue}
    if(key==="sourceChunkIds"){lines.push(`${indent}- 근거 구간: ${[].concat(item).map(id=>sectionLabel(Number(id))).join(", ")}`);continue}
    if(typeof item==="object"&&item!==null)lines.push(`${indent}${humanize(key)}\n${plainText(item,depth+1)}`);
    else lines.push(`${indent}- ${humanize(key)}: ${displayValue(item)}`)
  }
  return lines.length?lines.join("\n"):"-"
}
function safeFilename(value){return String(value).replace(/[\\/:*?"<>|\u0000-\u001f]/g,"_").replace(/\s+/g," ").trim().slice(0,100)||"도서"}
function showTab(key,data){state.currentTabKey=key;const root=$("#detail-content");root.replaceChildren();let value;if(key==="summary"){const reportSections=data.analysis?.sections;value={summaryShort:data.summary?.summaryShort||"",detailedSummary:data.summary?.summaryLong||(Array.isArray(reportSections)?reportSections:[]),uncertainties:data.summary?.uncertainties||[]}}else if(key==="sections")value=data.analysis.sections||data.chunks.chunks;else if(key==="timeline")value=data.timeline.timeline;else if(key==="relationships")value=data.relationships.relationships;else value=data.analysis.analysis?.[key]||[];appendValue(root,value,key,0)}
function appendValue(root,value,label,depth=0){
  if(value==null||value===""){appendText(root,"p","이 항목에는 확인된 분석이 없습니다.","empty");return}
  if(typeof value==="string"){appendReportText(root,value,label,depth);return}
  if(Array.isArray(value)){
    if(["detailedSummary","sections"].includes(label)){value.forEach((item,index)=>appendReportSection(root,item,index,label));return}
    const list=document.createElement("ul");list.className="report-list";
    value.forEach(v=>{const item=document.createElement("li");if(typeof v==="object"&&v!==null)item.className="report-item";appendValue(item,v,label,depth+1);list.append(item)});
    root.append(list);return
  }
  if(typeof value==="object"){
    const chunkId=Number(value.chunkId||0);
    if(chunkId)appendText(root,"h2",`${sectionLabel(chunkId)}${value.title?` · ${String(value.title)}`:""}`);
    for(const [k,v] of Object.entries(value)){
      if(["chunkId","charCount","position","uncertain"].includes(k)||(k==="title"&&chunkId))continue;
      if(k==="sourceChunkIds"){if(state.showEvidence)appendEvidence(root,v);continue}
      if(k==="description"||k==="keyPoints"){appendValue(root,v,k,depth+1);continue}
      if(["summaryShort","summaryLong","summary"].includes(k)){if(!(k==="summary"&&chunkId))appendText(root,depth>1?"h4":"h3",humanize(k));appendValue(root,v,k,depth+1);continue}
      if(["name","title","point","time"].includes(k)&&typeof v!=="object"){appendText(root,depth?"strong":"h3",String(v),"item-title");continue}
      if(typeof v==="object"&&v!==null){appendText(root,depth>1?"h4":"h3",humanize(k));appendValue(root,v,k,depth+1)}
      else{const row=document.createElement("p");row.className="report-line";appendText(row,"strong",`${humanize(k)}: `);row.append(document.createTextNode(displayValue(v)));root.append(row)}
    }
    return
  }
  appendText(root,"span",displayValue(value))
}
function appendReportSection(root,item,index,label){if(typeof item!=="object"||item==null){appendText(root,"h2",sectionLabel(index+1));appendValue(root,item,label,1);return}const sourceId=Number(item.chunkId||index+1),title=String(item.title||"").trim(),heading=label==="sections"?`${sectionLabel(sourceId)}${title?` · ${title}`:""}`:`${index+1}. ${title||sectionLabel(sourceId)}`;appendText(root,"h2",heading);for(const [key,value] of Object.entries(item)){if(["chunkId","charCount","position","title","uncertain"].includes(key))continue;if(key==="sourceChunkIds"){if(state.showEvidence)appendEvidence(root,value);continue}if(key==="description"||key==="summary"||key==="bullets"||key==="keyPoints"){appendValue(root,value,key,1);continue}appendText(root,"h3",humanize(key));appendValue(root,value,key,1)}}
function appendReportText(root,textValue,label,depth){const text=String(textValue).trim(),lines=text.split(/\r?\n/).filter(line=>line.trim());if(lines.some(line=>/^\s*(?:#{1,4}\s+|\d+[.)]\s+|-\s+)/.test(line))){let list=null;lines.forEach(line=>{const value=line.trim();const heading=value.match(/^(?:#{1,4}\s+)?(\d+)[.)]\s+(.+)$/);if(heading){list=null;appendText(root,"h2",`${heading[1]}. ${heading[2]}`);return}const bullet=value.match(/^-\s+(.+)$/);if(bullet){if(!list){list=document.createElement("ul");list.className="report-list";root.append(list)}appendText(list,"li",bullet[1]);return}list=null;appendText(root,"p",value)});return}if(["summaryLong","detailedSummary","summary"].includes(label)&&text.length>120){const sentences=text.match(/[^.!?。]+[.!?。]?/g)?.map(item=>item.trim()).filter(Boolean)||[text];const list=document.createElement("ul");list.className="report-list";sentences.forEach(sentence=>appendText(list,"li",sentence));root.append(list);return}appendText(root,depth>1?"span":"p",text)}
function appendEvidence(root,value){const ids=[...new Set([].concat(value).map(Number).filter(Number.isFinite))];if(!ids.length)return;const details=document.createElement("details");details.className="evidence-details";const summary=document.createElement("summary");summary.textContent="근거 구간 보기";details.append(summary);const list=document.createElement("ul");ids.forEach(id=>{const item=document.createElement("li"),button=document.createElement("button");button.type="button";button.className="evidence-link";button.textContent=`${sectionLabel(id)} 원문`;button.onclick=()=>{$("#chunk-select").value=String(id);openSelectedChunk()};item.append(button);list.append(item)});details.append(list);root.append(details)}
function sectionLabel(value){return`제${Number(value).toLocaleString("ko-KR")}구간`}
function displayValue(value){if(value==null)return"-";if(value===true)return"예";if(value===false)return"아니요";return String(value)}
function humanize(k){return({summaryShort:"핵심 요약",summaryLong:"상세 요약",detailedSummary:"상세 요약",summary:"요약",keyPoints:"",analysis:"분석",uncertainties:"불확실한 사항",characters:"주요 등장인물",relationships:"관계 변화",settings:"배경 변화",conflicts:"갈등 변화",plot:"사건과 전개",themes:"주제",symbols:"상징",concepts:"주요 개념",thesis:"핵심 논지",arguments:"논증 구조",methodology:"방법론",evidence:"근거",limitations:"한계",propositions:"핵심 명제",premises:"전제",objections:"반론",replies:"재반론",people:"주요 인물",events:"주요 사건",chronology:"연대기",causality:"원인과 결과",factions:"세력 관계",principles:"원리",mechanisms:"작동 원리",experiments:"실험",formulas:"공식",dependencies:"의존 관계",applications:"적용",claims:"주장",examples:"사례",perspective:"관점 변화",insights:"통찰",procedures:"절차",checklists:"확인 목록",cautions:"주의사항",failureFactors:"실패 요인",scenes:"장면 구성",dialogue:"대사와 극적 기능",stage:"무대와 연출 단서",speakers:"화자",imagery:"이미지",motifs:"모티프",form:"형식과 리듬",composition:"구성",contrasts:"작품 간 대비",contributors:"기여자",structure:"구조",genre:"장르",confidence:"신뢰도",reasons:"판단 근거",uncertain:"불확실 여부",documentType:"문서 유형",author:"저자",filename:"원본 파일",indexStatus:"분석 상태",indexedAt:"분석 시각"}[k]??"기타 정보")}
function appendText(root,tag,text,className){const el=document.createElement(tag);if(className)el.className=className;el.textContent=text;root.append(el);return el}

function missingSettings(items){return items.filter(([,v])=>!v||String(v).startsWith("REPLACE_")).map(([name])=>name)}
function oauthConfigurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId]])}
function pickerConfigurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId],["Google Cloud 프로젝트 번호",config.googleCloudProjectNumber],["Google Picker API Key",config.googlePickerApiKey]])}
function configurationIssues(){return missingSettings([["Google OAuth Client ID",config.googleClientId],["Google Picker API Key",config.googlePickerApiKey],["Apps Script Web App URL",config.appsScriptWebAppUrl]])}
function showConfigurationState(){const issues=configurationIssues(),alert=$("#setup-alert");if(!issues.length){alert.hidden=true;return}alert.hidden=false;alert.textContent=`관리 기능 설정이 아직 끝나지 않았습니다: ${issues.join(", ")}. README의 ‘Picker와 Apps Script 연결’ 단계를 완료해야 폴더 선택·API 키 저장·실시간 모니터가 작동합니다.`}
async function waitForGoogleScripts(){const limit=Date.now()+12000;while(Date.now()<limit){if(window.google?.accounts?.oauth2&&window.gapi)return;await new Promise(r=>setTimeout(r,250))}throw new Error("Google 로그인 스크립트를 불러오지 못했습니다. 광고 차단을 끄고 새로고침하세요.")}
async function getAccessToken(forceConsent=false){const issues=oauthConfigurationIssues();if(issues.length)throw new Error(`설정 필요: ${issues.join(", ")}`);if(state.accessToken&&Date.now()<state.tokenExpiresAt-60000)return state.accessToken;await waitForGoogleScripts();return new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:config.googleClientId,scope:"openid email https://www.googleapis.com/auth/drive.readonly",callback:r=>{if(r.error||!r.access_token){reject(new Error(r.error_description||r.error||"Google 인증 실패"));return}state.accessToken=r.access_token;state.tokenExpiresAt=Date.now()+Number(r.expires_in||3600)*1000;$("#monitor-connection").textContent="Google 계정 연결됨 · 5초마다 자동 갱신";startMonitoring();resolve(state.accessToken)},error_callback:e=>reject(new Error(e.message||e.type||"Google 로그인 창을 열지 못했습니다."))});client.requestAccessToken({prompt:forceConsent?"consent":""})})}
function loadPickerApi(){return new Promise((resolve,reject)=>{let settled=false;const finish=fn=>value=>{if(!settled){settled=true;fn(value)}};gapi.load("picker",{callback:finish(resolve),onerror:finish(()=>reject(new Error("Google Picker를 불러오지 못했습니다."))),timeout:12000,ontimeout:finish(()=>reject(new Error("Google Picker 응답 시간이 초과되었습니다.")))})})}
async function openPicker(){const button=$("#pick-folder");button.disabled=true;message("Google 로그인과 폴더 선택기를 준비하고 있습니다…");try{const issues=pickerConfigurationIssues();if(issues.length)throw new Error(`설정 필요: ${issues.join(", ")}`);const token=await getAccessToken();await loadPickerApi();buildPicker(token)}catch(e){message(`폴더 선택 실패: ${e.message}`);$("#setup-alert").hidden=false;$("#setup-alert").textContent=`Google Drive 폴더 선택을 시작하지 못했습니다. ${e.message}`}finally{button.disabled=false}}
function buildPicker(token){const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);if(config.driveRootFolderId&&!config.driveRootFolderId.startsWith("REPLACE_"))view.setParent(config.driveRootFolderId);new google.picker.PickerBuilder().setOAuthToken(token).setDeveloperKey(config.googlePickerApiKey).setAppId(config.googleCloudProjectNumber).setOrigin(location.origin).addView(view).setCallback(data=>{if(data.action===google.picker.Action.PICKED){const d=data.docs[0];setSelectedFolder(d.id,d.name);message("폴더가 선택되었습니다. 먼저 대상 미리 보기를 권장합니다.")}else if(data.action===google.picker.Action.CANCEL)message("폴더 선택을 취소했습니다.")}).build().setVisible(true)}
function setSelectedFolder(id,name=""){if(!id)return;state.selectedFolder={id:String(id),name:String(name||"")};$("#folder-info dd").textContent=name?`${name} (${id})`:`현재 인덱싱 폴더 (${id})`;$("#preview-index").disabled=false;$("#start-index").disabled=false}
async function syncFolderFromStatus(status){const id=String(status?.folderId||"").trim();if(!id)return;const suppliedName=String(status?.folderName||"").trim(),knownName=state.selectedFolder?.id===id?state.selectedFolder.name:"",name=suppliedName||knownName;setSelectedFolder(id,name);if(name||!state.accessToken)return;try{const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id%2Cname%2CmimeType&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${state.accessToken}`},cache:"no-store"});if(!response.ok)return;const folder=await response.json();if(folder.name)setSelectedFolder(id,folder.name)}catch(error){console.warn("현재 인덱싱 폴더 이름 확인 생략",error)}}
async function relayRequest(payload,requireToken=true){if(!config.appsScriptWebAppUrl||config.appsScriptWebAppUrl.startsWith("REPLACE_"))throw new Error("Apps Script Web App URL이 설정되지 않았습니다.");const accessToken=requireToken?await getAccessToken():"";const response=await fetch(config.appsScriptWebAppUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...payload,...(accessToken?{accessToken}:{})})});if(!response.ok)throw new Error(`Apps Script HTTP ${response.status}`);const data=await response.json();if(!data.ok)throw new Error(data.error||"요청 실패");return data}
async function relay(route){if(!state.selectedFolder){message("먼저 Google Drive 폴더를 선택하세요.");return}if(route==="dispatch"&&state.dispatching){message("인덱싱 요청을 이미 전달하고 있습니다.");return}const start=$("#start-index");if(route==="dispatch"){state.dispatching=true;start.disabled=true}message(route==="preview"?"대상을 확인하는 중…":"GitHub Actions를 요청하는 중…");try{const data=await relayRequest({route,folderId:state.selectedFolder.id,folderName:state.selectedFolder.name,recursive:$("#recursive").checked,force:$("#force-reindex").checked});message(route==="preview"?`대상 TXT/EPUB ${data.targetFiles}개 · 하위 폴더 ${data.folders}개`:data.alreadyRunning?(data.message||"이미 인덱싱 작업이 실행 또는 대기 중입니다."):`작업 요청 완료 · GitHub 실행 ID ${data.runId||"확인 중"}`);if(route==="dispatch")startMonitoring()}catch(e){message(`요청 실패: ${e.message}`)}finally{if(route==="dispatch"){state.dispatching=false;start.disabled=false}}}
async function saveApiKey(){const input=$("#gemini-key"),key=input.value.trim(),output=$("#api-key-message");if(!/^[A-Za-z0-9._-]{20,300}$/.test(key)){output.textContent="올바른 Gemini API Key를 입력하세요.";return}$("#save-api-key").disabled=true;$("#api-key-state").textContent="저장 중";$("#api-key-state").className="state-badge pending";output.textContent="Google 계정을 확인하고 안전하게 저장하는 중…";try{const data=await relayRequest({route:"update-api-key",geminiApiKey:key});input.value="";input.type="password";$("#toggle-key").textContent="보기";renderApiKeyStatus(data.geminiKey,true);output.textContent="서버 저장을 확인했습니다. GitHub 기본 Secret 대신 이 키를 다음 인덱싱부터 사용합니다."}catch(e){$("#api-key-state").textContent="저장 실패";$("#api-key-state").className="state-badge error";output.textContent=`저장 실패: ${e.message}`}finally{$("#save-api-key").disabled=false}}
function renderApiKeyStatus(key,justSaved=false){const configured=Boolean(key?.configured),stateBadge=$("#api-key-state");stateBadge.textContent=configured?"저장 확인됨":"별도 키 없음";stateBadge.className=`state-badge ${configured?"verified":""}`;$("#api-key-mask").textContent=configured?(key.masked||"끝자리 확인 불가"):"GitHub 기본 Secret 사용";$("#api-key-updated").textContent=configured?formatTime(key.updatedAt):"-";$("#api-key-use").textContent=configured?(justSaved?"다음 인덱싱부터 새 키 사용":"현재 저장된 키를 다음 실행에 사용"):"GitHub 기본 Secret을 사용"}
async function connectMonitor(){const output=$("#monitor-connection");output.textContent="Google 계정 확인 중…";try{await getAccessToken();await pollLiveStatus()}catch(e){output.textContent=`연결 실패: ${e.message}`}}
async function loadJobStatus(){try{const saved=await fetchJSON("data/job-status.json");await syncFolderFromStatus(saved);renderJobStatus(saved,false)}catch(e){$("#job-status").textContent="저장된 작업 상태를 불러오지 못했습니다."}}
function startMonitoring(){if(state.monitorTimer)clearInterval(state.monitorTimer);pollLiveStatus();state.monitorTimer=setInterval(pollLiveStatus,5000)}
async function pollLiveStatus(){if(!state.accessToken||location.hash.slice(1).split("/")[0]!=="indexing")return;try{const data=await relayRequest({route:"status"});let progress=await reconcileQueuedStatus(data.progress||{});await syncFolderFromStatus(progress);if(["COMPLETE","ERROR","PAUSED_RATE_LIMIT","PAUSED_SERVICE_UNAVAILABLE","NO_SUPPORTED_MODEL"].includes(progress.status)){try{const saved=await fetchJSON(`data/job-status.json?status=${Date.now()}`),sameRun=saved.startedAt&&progress.startedAt?saved.startedAt===progress.startedAt:saved.status===progress.status&&saved.currentFileName===progress.currentFileName;if(sameRun){if(!saved.lastError&&Array.isArray(saved.errors)&&saved.errors[0]?.error)saved.lastError=saved.errors[0].error;if(!saved.message&&saved.lastError)saved.message=`책 처리 오류: ${saved.lastError}`;const liveUpdatedAt=progress.updatedAt;progress={...progress,...saved,...(liveUpdatedAt?{updatedAt:liveUpdatedAt}:{})}}}catch(e){console.warn("저장된 상세 상태 병합 생략",e)}}renderJobStatus(progress,true);const key=data.geminiKey||{};renderApiKeyStatus(key);$("#api-key-message").textContent=key.configured?"Apps Script 서버에서 저장된 키를 확인했습니다.":"Apps Script에 별도 키가 없어 GitHub 기본 Secret을 사용합니다."}catch(e){$("#monitor-connection").textContent=`실시간 갱신 실패: ${e.message}`}}
async function reconcileQueuedStatus(progress){if(progress.status!=="QUEUED"){state.queueResolvedStatus=null;return progress}const updated=Date.parse(progress.updatedAt||"");if(!updated||Date.now()-updated<60000||!config.githubRepository)return progress;if(state.queueResolvedStatus)return{...progress,...state.queueResolvedStatus};if(Date.now()-state.queueCheckAt<30000)return progress;state.queueCheckAt=Date.now();try{const response=await fetch(`https://api.github.com/repos/${config.githubRepository}/actions/workflows/index-books.yml/runs?event=workflow_dispatch&per_page=1`,{cache:"no-store"});if(!response.ok)return progress;const run=(await response.json()).workflow_runs?.[0];if(!run||Date.parse(run.created_at)<updated-120000)return progress;const common={runId:String(run.id||""),runUrl:run.html_url||""};if(run.status==="in_progress")state.queueResolvedStatus={...common,status:"RUNNING",phase:"PREPARING",message:"GitHub 실행기가 시작되어 설정과 테스트를 확인하고 있습니다."};else if(run.status==="completed")state.queueResolvedStatus={...common,status:"ERROR",phase:"ERROR",lastError:`GitHub 사전 단계 ${run.conclusion||"실패"}`,message:"GitHub 작업은 종료됐지만 인덱싱이 시작되지 않았습니다. 준비 또는 사전 테스트 단계의 오류입니다."};return state.queueResolvedStatus?{...progress,...state.queueResolvedStatus}:progress}catch(error){console.warn("GitHub 대기 상태 확인 생략",error);return progress}}
const phaseLabels={WAITING:"대기",QUEUED:"실행 대기",PREPARING:"실행 환경 준비",DISCOVERY_COMPLETE:"파일 목록 확인",STARTING_BOOK:"책 처리 시작",UNCHANGED:"변경 없음",DOWNLOADING:"Drive 다운로드",METADATA:"제목·저자 판별",CLASSIFYING:"문서 유형 분류",ANALYZING_CHUNK:"원문 구간 분석",SYNTHESIZING:"전체 분석 통합",SAVING:"결과 저장",BOOK_FINISHED:"책 처리 완료",BOOK_ERROR:"책 처리 오류",GEMINI_RETRY:"Gemini 일시 오류 재시도",GEMINI_PACING:"무료 호출 간격 조절",INVALID_JSON_RETRY:"JSON 응답 자동 복구",MODEL_FALLBACK:"다음 무료 모델로 전환",MODEL_COOLDOWN:"전 모델 쿨다운",MODEL_CYCLE_RESTART:"무료 모델 다시 탐색",COMPLETE:"전체 완료",ERROR:"처리 오류",PAUSED_RATE_LIMIT:"무료 한도 일시정지",PAUSED_SERVICE_UNAVAILABLE:"Gemini 서비스 일시정지",NO_SUPPORTED_MODEL:"지원 모델 없음"};
function renderJobStatus(incoming,live){
  const derivedError=incoming.lastError||(Array.isArray(incoming.errors)&&incoming.errors[0]?.error)||"";
  if(derivedError)incoming={...incoming,lastError:derivedError,...(!incoming.message?{message:`책 처리 오류: ${derivedError}`}:{})};
  if(incoming.status==="QUEUED"||(incoming.startedAt&&state.lastStatus?.startedAt&&incoming.startedAt!==state.lastStatus.startedAt))state.lastStatus=null;
  state.lastStatus={...(state.lastStatus||{}),...incoming};
  const s=state.lastStatus,root=$("#job-status");root.replaceChildren();
  const total=Number(s.totalFiles||0),index=Number(s.currentFileIndex||0),resolved=Number(s.complete||0)+Number(s.skipped||0),percent=total?Math.min(100,resolved/total*100):0;
  $("#overall-progress").style.width=`${percent}%`;
  $("#progress-caption").textContent=total?`완료·건너뜀 ${resolved.toLocaleString()} / 전체 ${total.toLocaleString()} · ${percent.toFixed(2)}%${index?` · 현재 ${index.toLocaleString()}번째 파일`:""}`:"대상 파일 수를 확인하는 중입니다.";
  const indicator=$("#live-indicator");indicator.textContent=live?"실시간 · 5초 갱신":"저장된 상태";indicator.classList.toggle("live",live);
  const attempts=s.apiRequestAttempts??s.apiRequests??0,success=s.apiSuccessfulRequests??"정보 없음",failed=s.apiFailedAttempts??"정보 없음",models=Array.isArray(s.attemptedModels)?s.attemptedModels.join(" → "):(s.model||"아직 선택 전"),retry=s.retryAttempt?`${s.retryAttempt} / ${s.retryMaxAttempts||"-"}`:"-",delay=s.retryDelaySeconds!=null?`${s.retryDelaySeconds}초`:"-",cycle=s.maxModelCycles?`${s.modelCycle||1} / ${s.maxModelCycles}`:(s.modelCycle||1);
  const groups=[
    ["현재 작업",[["상태",s.status||"-"],["현재 단계",phaseLabels[s.phase]||s.phase||"-"],["현재 파일",s.currentFileName||"-"],["파일 순서",total?`${index} / ${total}`:"-"],["현재 구간",s.totalChunks?`${s.currentChunk||0} / ${s.totalChunks}`:"-"],["마지막 갱신",formatTime(s.updatedAt||s.finishedAt)]]],
    ["모델 및 재시도",[["선택 모델",s.model||"아직 선택 전"],["이전 모델",s.previousModel||"-"],["시도한 모델",models],["모델 전환",s.modelSwitchCount??0],["모델 순환",cycle],["순환 재시작",s.modelCycleRestarts??0],["최근 HTTP",s.lastHttpStatus||"-"],["재시도 횟수",retry],["대기 시간",delay]]],
    ["처리 결과",[["완료",s.complete??0],["건너뜀",s.skipped??0],["실패",s.failed??0],["메타 확인 필요",s.metadataReview??0],["JSON 문법 오류",s.invalidJsonResponses??0]]],
    ["무료 사용량",[["Gemini 호출",attempts],["성공 응답",success],["실패 시도",failed],["입력 토큰",Number(s.inputTokens||0).toLocaleString()],["출력 토큰",Number(s.outputTokens||0).toLocaleString()],["Drive 사용량",s.driveQuotaUnits??0],["Drive 다운로드",formatBytes(s.driveDownloadedBytes)]]]
  ];
  const dashboard=document.createElement("div");dashboard.className="status-dashboard";
  groups.forEach(([title,rows])=>{const section=document.createElement("section");section.className="status-group";appendText(section,"h3",title);const grid=document.createElement("dl");grid.className="status-table";rows.forEach(([key,value])=>{const row=document.createElement("div");appendText(row,"dt",String(key));appendText(row,"dd",String(value));grid.append(row)});section.append(grid);dashboard.append(section)});
  root.append(dashboard);
  if(s.message)appendText(root,"p",s.message,"status-message");
  if(s.lastModelError&&s.lastModelError!==s.message)appendText(root,"p",`최근 모델 오류: ${s.lastModelError}`,"status-message");
  if(s.runUrl){const link=document.createElement("a");link.href=s.runUrl;link.target="_blank";link.rel="noopener noreferrer";link.className="run-link";link.textContent="GitHub 실행 상세 보기 ↗";root.append(link)}
  recordActivity(s)
}
function recordActivity(s){const stamp=s.updatedAt||s.finishedAt;if(!stamp||(!s.phase&&!s.status))return;const label=phaseLabels[s.phase]||s.phase||s.status||"상태 변경",key=[label,s.currentFileName,s.currentChunk,s.model,s.message].join("|");if(!key||key===state.lastActivityKey)return;state.lastActivityKey=key;const log=$("#activity-log");if(log.children.length===1&&log.firstElementChild.textContent==="모니터 연결 대기 중")log.replaceChildren();const first=log.firstElementChild;if(first&&first.dataset.activityKey===key)return;const item=document.createElement("li");item.dataset.activityKey=key;item.textContent=`${formatTime(stamp)} · ${label}${s.currentFileName?` · ${s.currentFileName}`:""}`;log.prepend(item);while(log.children.length>12)log.lastElementChild.remove()}
function formatBytes(value){const bytes=Number(value||0);if(!bytes)return"0 B";const units=["B","KB","MB","GB"],i=Math.min(units.length-1,Math.floor(Math.log(bytes)/Math.log(1024)));return`${(bytes/1024**i).toFixed(i?1:0)} ${units[i]}`}
function formatTime(value){if(!value)return"-";const date=new Date(value);return Number.isNaN(date.valueOf())?String(value):date.toLocaleString("ko-KR")}
function message(text){$("#index-message").textContent=text}
load().catch(e=>{console.error(e);$("#results").textContent=`초기 데이터를 읽지 못했습니다: ${e.message}`});
